name: example
description: Charts-Flutter Demo
environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.8.0"

dependencies:
  charts_flutter:
    path: ../
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
