name: charts_common
version: 0.12.0
description: A common library for charting packages.
homepage: https://github.com/google/charts

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.8.0"

dependencies:
  intl: ^0.19.0
  logging: ^1.0.2
  vector_math: ^2.0.8

dev_dependencies:
  mockito: ^5.0.0
  test: ^1.5.3
